
<!-- Simple login form -->
<?php 
$form = $this->loginForm;
$form->prepare();
echo $this->form()->openTag($form);
?>
    <input type="hidden" name="baseUrl" value="<?php echo $baseUrl; ?>">
	<div class="panel panel-body login-form">
		<div class="text-center">
			<div class="icon-object border-slate-300 text-slate-300"><i class="icon-reading"></i></div>
			<h5 class="content-group">Sign to your account <small class="display-block">Enter your credentials below</small></h5>
		</div>

		<div class="form-group has-feedback has-feedback-left">			
			<!--<input type="text" class="form-control" placeholder="Username">-->
			<?php echo $this->formElement($form->get('username')); ?>
			<div class="form-control-feedback">
			<i class="icon-user text-muted"></i>
			</div>
		</div>

		<div class="form-group has-feedback has-feedback-left">
			<!--<input type="password" class="form-control" placeholder="Password">-->
			<?php echo $this->formElement($form->get('password')); ?>
			<div class="form-control-feedback">
				<i class="icon-lock2 text-muted"></i>
			</div>
		</div>
		
		<?php if($error_message != ''){ ?>
            <div class="alert alert-danger alert-bordered">
                <button type="button" class="close" data-dismiss="alert"><span>&times;</span><span class="sr-only">Close</span></button>
                <?php echo $error_message; ?>
			 </div>
		<?php  } ?>
		
		<div class="form-group">
			<!--<button type="submit" class="btn btn-primary btn-block">Sign in <i class="icon-circle-right2 position-right"></i></button>-->
			<?php
				echo $this->formRow($form->get('loginCsrf'));
				echo $this->formElement($form->get('submit'));
			?>
		</div>
		
	</div>
<?php
echo $this->form()->closeTag($form);
?>
<!-- /simple login form -->

