<?php
 $title = 'All Companies';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('company', array('action'=>'add'));?>">Add new company</a>
 </p>

 <table class="table">
 <tr>
     <th>Company Name</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($companies as $company) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($company->company_name);?></td>
     <td>
         <a href="<?php echo $this->url('company',
             array('action'=>'edit', 'id' => $company->company_id));?>">Edit</a>
         <a href="<?php echo $this->url('company',
             array('action'=>'delete', 'id' => $company->company_id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>