<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Reports\Module'                        => __DIR__ . '/Module.php',
    'Reports\Controller\SaresReportsController' => __DIR__ . '/src/Reports/Controller/SaresReportsController.php',
    'ReportsTest\Framework\TestCase'        => __DIR__ . '/tests/Reports/Framework/TestCase.php',
    'ReportsTest\SampleTest'                => __DIR__ . '/tests/Reports/SampleTest.php',
);
