<?php

 $title = 'Add Admin User';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('member', array('action' => 'add-member-user')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('adm'));
 echo $this->formHidden($form->get('user_id'));
 echo $this->formRow($form->get('username'));
 echo "<br>";
 echo $this->formRow($form->get('password'));
 echo "<br>";
 echo $this->formRow($form->get('name'));
 echo "<br>";
 echo $this->formRow($form->get('member_id'));
 echo "<br>";
 echo $this->formRow($form->get('phone'));
 echo "<br>";
 echo $this->formRow($form->get('email'));
 echo "<br>";
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 ?>