<?php

 $title = 'Add new member';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('member', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('member_name'));
 echo "<br>";
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 ?>