 <?php
 $title = 'Edit member';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'member',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('member_name'));
 echo '<br>';
 echo $this->formRow($form->get('is_active'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 ?>
 <a href="<?php echo $this->url('member', array('action'=>'index'));?>">Back</a>