<?php
 $title = 'All members';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('member', array('action'=>'add'));?>">Add new member</a>
 </p>

 <table class="table">
 <tr>
     <th>Member Name</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($members as $member) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($member->member_name);?></td>
     <td>
         <a href="<?php echo $this->url('member',
             array('action'=>'edit', 'id' => $member->member_id));?>">Edit</a>
         <a href="<?php echo $this->url('member',
             array('action'=>'delete', 'id' => $member->member_id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>