<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Member\Module'                        => __DIR__ . '/Module.php',
    'Member\Controller\MemberController' => __DIR__ . '/src/Member/Controller/MemberController.php',
	'Member\Controller\UserController' => __DIR__ . '/src/Member/Controller/UserController.php',
	'Member\Controller\RoleController' => __DIR__ . '/src/Member/Controller/RoleController.php',
	'Member\Controller\UserGroupController' => __DIR__ . '/src/Member/Controller/UserGroupController.php',
	'MemberTest\Framework\TestCase'        => __DIR__ . '/tests/Member/Framework/TestCase.php',
    'MemberTest\SampleTest'                => __DIR__ . '/tests/Member/SampleTest.php',
);
